src/Entity/OrderRow.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrderRowRepository")
 */
class OrderRow
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /** @ORM\Column(type="integer") */
    private $Quantity;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Orders", inversedBy="Order_Row_ID")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Order_ID;

    /** @ORM\OneToMany(targetEntity="App\Entity\Item", mappedBy="Order_Row_ID") */
    private $Item_ID;

    public function __construct()
    {
        $this->Item_ID = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }

    public function getOrderID(): ?Orders
    {
        return $this->Order_ID;
    }

    public function setOrderID(?Orders $Order_ID): self
    {
        $this->Order_ID = $Order_ID;

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItemID(): Collection
    {
        return $this->Item_ID;
    }

    public function addItemID(Item $itemID): self
    {
        if (!$this->Item_ID->contains($itemID)) {
            $this->Item_ID[] = $itemID;
            $itemID->setOrderRowID($this);
        }

        return $this;
    }

    public function removeItemID(Item $itemID): self
    {
        if ($this->Item_ID->contains($itemID)) {
            $this->Item_ID->removeElement($itemID);
            // set the owning side to null (unless already changed)
            if ($itemID->getOrderRowID() === $this) {
                $itemID->setOrderRowID(null);
            }
        }

        return $this;
    }
}

src/Controller/Rest/Basket/Basket.php
<?php

declare(strict_types=1);

namespace App\Controller\Rest\Basket;

use App\Entity\Item;
use App\Entity\OrderRow;
use App\Entity\Orders;
use App\Entity\User;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\View\View;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

class Basket extends AbstractController
{
    /**
     * @Rest\Post("/add_to_basket", name="add_to_basket")
     */
    public function addToBasket(Request $request): View
    {
        $em = $this->getDoctrine()->getManager();
        $userID = $request->get('user_id');
        $productID = $request->get('product_id');
        $productQuantity = intval($request->get('product_quantity'));
        $users = $em->getRepository(User::class);
        $products = $em->getRepository(Item::class);

        $user = $users->findOneBy(['id' => $userID]);
        $product = $products->findOneBy(['id' => $productID]);

        if (!$user || !$product) {
            return View::create('not found', 404);
        }

        $userOrders = $em->getRepository(Orders::class)->createQueryBuilder('userOrder')
            ->where('userOrder.isFinished = false')
            ->andWhere('userOrder.User_ID = :user')
            ->setParameter('user', $user)
            ->getQuery()
            ->execute()
        ;


        if (!$userOrders) {
            /** @var Orders $order */
            $order = new Orders();

            /** @var OrderRow $orderRow */
            $orderRow = new OrderRow();

            $orderRow->addItemID($product);
            $orderRow->setQuantity($productQuantity);

            $order->setTotalQuantity($productQuantity);
            $order->setSumPrice($productQuantity * $product->getItemPrice());
            $order->setUserID($user);
            $order->setOrderDate(date('d/m/y H:i:s'));
            $order->addOrderRowID($orderRow);
            $em->persist($orderRow);
            $em->persist($order);
            $em->flush();

            return View::create($order->getTotalQuantity(), 201);
        }

        /** @var Orders|null $userOrder */
        $userOrder = $em->getRepository(Orders::class)->createQueryBuilder('userOrder')
            ->leftJoin('userOrder.Order_Row_ID', 'orderRow')
            ->where('userOrder.isFinished = false')
            ->andWhere('orderRow.Order_ID = userOrder.id')
            ->andWhere('userOrder.User_ID = :user')
            ->setParameter('user', $user)
            ->orderBy('userOrder.id', 'DESC')
            ->getQuery()
            ->getOneOrNullResult()
        ;

        if ($userOrder) {
            /** @var OrderRow|null $orderRow */
            $orderRow = $em->getRepository(OrderRow::class)->createQueryBuilder('orderRow')
                ->leftJoin('orderRow.Order_ID', 'userOrder')
                ->leftJoin('orderRow.Item_ID', 'product')
                ->where('orderRow.Order_ID = userOrder')
                ->andWhere('product.id = :item')
                ->setParameter('item', $product->getId())
                ->getQuery()
                ->getOneOrNullResult()
            ;

            if (!$orderRow) {
                /** @var OrderRow $orderRow */
                $orderRow = new OrderRow();

                $orderRow->addItemID($product);
                $orderRow->setQuantity($productQuantity);

                $userOrder->addOrderRowID($orderRow);

                $totalQuantity = $userOrder->getTotalQuantity() + $productQuantity;

                $userOrder->setTotalQuantity($totalQuantity);
                $newPrice = $userOrder->getSumPrice() + $product->getItemPrice() * $productQuantity;
                $userOrder->setSumPrice($newPrice);
                $em->persist($orderRow);
                $em->persist($userOrder);
                $em->flush();

                return View::create($totalQuantity, 201);
            }

            $newQuantity = $orderRow->getQuantity() + $productQuantity;
            $orderRow->setQuantity($newQuantity);

            $em->persist($orderRow);

            $newTotalQuantity = $userOrder->getTotalQuantity() + $productQuantity;
            $newSumPrice = $userOrder->getSumPrice() + $product->getItemPrice() * $productQuantity;

            $userOrder->setSumPrice($newSumPrice);
            $userOrder->setTotalQuantity($newTotalQuantity);

            $em->persist($userOrder);
            $em->flush();

            return View::create($newTotalQuantity, 201);
        } else {
            $foundOrder = $em->getRepository(Orders::class)->createQueryBuilder('userOrder')
                ->where('userOrder.isFinished = false')
                ->andWhere('userOrder.User_ID = :user')
                ->setParameter('user', $user)
                ->orderBy('userOrder.id', 'DESC')
                ->getQuery()
                ->getOneOrNullResult()
            ;

            /** @var OrderRow $orderRow */
            $orderRow = new OrderRow();

            $orderRow->addItemID($product);
            $orderRow->setQuantity($productQuantity);

            $foundOrder->addOrderRowID($orderRow);

            $totalQuantity = $foundOrder->getTotalQuantity() + $productQuantity;

            $foundOrder->setTotalQuantity($totalQuantity);
            $newPrice = $foundOrder->getSumPrice() + $product->getItemPrice();
            $foundOrder->setSumPrice($newPrice);
            $em->persist($orderRow);
            $em->persist($foundOrder);
            $em->flush();

            return View::create($totalQuantity, 201);
        }

        return View::create('nothin', 201);
    }
}

src/Controller/Rest/Basket/GetAmount.php
<?php

declare(strict_types=1);

namespace App\Controller\Rest\Basket;

use App\Entity\Orders;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\View\View;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

class GetAmount extends AbstractController
{
    /**
     * @Rest\Get("/get_order_amount/{order_id}")
     */
    public function getAmount(Request $request, int $order_id): View
    {
        if (!$order_id) {
            return View::create('not enough data', 404);
        }

        $em = $this->getDoctrine()->getManager();

        $order = $em->getRepository(Orders::class)->find($order_id);

        if (!$order) {
            return View::create('not found', 404);
        }

        return View::create($order->getSumPrice(), 201);
    }
}

src/Controller/Web/BasketController.php
<?php

declare(strict_types=1);

namespace App\Controller\Web;

use App\Entity\Item;
use App\Entity\Orders;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BasketController extends AbstractController
{
    /**
     * @Route("/basket", name="basket")
     */
    public function index(): Response
    {
        $em = $this->getDoctrine()->getManager();

        $user = $this->getUser();

        if (!$user) {
            return $this->render('error.html.twig', [
                'exceptionTitle' => 'not logged in',
                'exception' => 'this site is for users only',
            ]);
        }

        /** @var Orders $order */
        $order = $em->getRepository(Orders::class)->createQueryBuilder('o')
            ->where('o.isFinished = :order_state')
            ->andWhere('o.User_ID = :userID')
            ->setParameter('order_state', false)
            ->setParameter('userID', $user->getId())
            ->orderBy('o.id', 'desc')
            ->setMaxResults(1)
            ->getQuery()
            ->getOneOrNullResult()
        ;

        $orderRows = [];
        $items = [];

        if (!$order) {
            return $this->render('error.html.twig', [
                'exceptionTitle' => 'no order',
                'exception' => 'basket is empty',
            ]);
        }
        $orderItems = $order->getOrderRowID()->current();

        foreach ($order->getOrderRowID() as $orderRow) {
            $orderRows[] = $orderRow;
        }

        if (empty($orderItems)) {
            return $this->render('error.html.twig', [
                'exceptionTitle' => 'cart empty',
                'exception' => 'cart is empty',
            ]);
        }

        /** @var Item $orderItem */
        foreach ($orderItems->getItemID() as $orderItem) {
            $items[] = $orderItem;
        }

        return $this->render('basket/index.html.twig', [
            'orderRow' => $orderRows,
        ]);
    }
}

templates/basket/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BasketController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <div class="cart-list">
        {% set totalprice = 0 %}
        {% set totalquantity = 0 %}
        {% for order in orderRow %}
            {% for item in order.itemid %}
                <div class="product-widget">
                    <div class="product-img">
                        {% set item_images = item.images %}
                        {% if item_images[0] is defined %}
                            {% set image_url = 'uploads/images/' ~ item_images[0].source %}
                            <img src="{{ asset(image_url) }}" alt="">
                        {% endif %}

                        {# {% for image in item.images %}
                            {% set image_url = 'uploads/images/' ~ image.source %}
                            <img src="{{ asset(image_url) }}" alt="">
                            {% break %}
                        {% endfor %} #}
                    </div>
                    <div class="product-body">
                        <h3 class="product-name"><a href="#">{{ item }}</a></h3>
                        <h4 class="product-price"><span class="qty">{{ order.quantity }}x</span>{{ item.itemprice }} ZŁ => {{ item.itemprice * order.quantity }} ZŁ</h4>
                        <a onclick="removeOneItem({{ order.orderid.id }}, {{ item.id }})" id="remove-item" href="#" >
                            <i class="fa fa-close btn-danger"></i>
                        </a>
                    </div>
                    <a class="delete" onclick="removeItem({{ order.orderid.id }}, {{ item.id }})" id="remove-item" href="#" >
                        <i class="fa fa-close"></i>
                    </a>
                </div>
            {% set totalprice = totalprice + (item.itemprice * order.quantity) %}
            {% set totalquantity = totalquantity + order.quantity %}
            {% endfor %}
        {% endfor %}
    </div>
    <div class="cart-summary">
        <small>{{ totalquantity }} Item(s) selected</small>
        <h5>SUBTOTAL: {{ totalprice }} ZŁ</h5>
    </div>
    <a class="btn primary-btn" href="{{ path('checkout') }}">go to checkout</a>
</div>

<script>
    function removeItem(basketID, itemID) {
        let route = '/api/remove_item_from_basket';

        $.ajax({
            url: route,
            type: 'delete',
            data: {
                "basket_id": basketID,
                "product_id": itemID
            },
            success: function(result) {
                let cartAmountDiv = document.getElementById("cart_amount");

                if (parseInt(result) > 0) {
                    if (cartAmountDiv === null){
                        let cartAmountLinkDiv = document.getElementById("cart_amount_link");
                        let newDiv = document.createElement("div");
                        newDiv.id = "cart_amount";
                        newDiv.className = "qty";
                        cartAmountLinkDiv.appendChild(newDiv);

                        cartAmountDiv = document.getElementById("cart_amount");
                    }

                    cartAmountDiv.innerHTML = result.toString();
                } else {
                    if (cartAmountDiv !== null) {
                        cartAmountDiv.parentNode.removeChild(cartAmountDiv);
                    }
                }

                location.reload();
            }
        });
    }

    function removeOneItem(basketID, itemID) {
        let route = '/api/remove_one_item_from_basket';

        $.ajax({
            url: route,
            type: 'delete',
            data: {
                "basket_id": basketID,
                "product_id": itemID
            },
            success: function(result) {
                let cartAmountDiv = document.getElementById("cart_amount");

                if (parseInt(result) > 0) {
                    if (cartAmountDiv === null){
                        let cartAmountLinkDiv = document.getElementById("cart_amount_link");
                        let newDiv = document.createElement("div");
                        newDiv.id = "cart_amount";
                        newDiv.className = "qty";
                        cartAmountLinkDiv.appendChild(newDiv);

                        cartAmountDiv = document.getElementById("cart_amount");
                    }

                    cartAmountDiv.innerHTML = result.toString();
                } else {
                    if (cartAmountDiv !== null) {
                        cartAmountDiv.parentNode.removeChild(cartAmountDiv);
                    }
                }

                location.reload();
            }
        });
    }
</script>
{% endblock %}