src/Entity/Item.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ItemRepository")
 */
class Item
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /** @ORM\Column(type="string", length=255) */
    private $name;

    /** @ORM\Column(type="string", length=255) */
    private $description;

    /** @ORM\Column(type="decimal", precision=5, scale=2) */
    private $width;

    /** @ORM\Column(type="decimal", precision=10, scale=0) */
    private $height;

    /** @ORM\Column(type="integer") */
    private $item_amount;

    /** @ORM\Column(type="decimal", precision=10, scale=0) */
    private $item_price;

    /** @ORM\ManyToOne(targetEntity="App\Entity\OrderRow", inversedBy="Item_ID") */
    private $Order_Row_ID;

    /** @ORM\ManyToMany(targetEntity="App\Entity\ItemCategory", mappedBy="Item_ID") */
    private $Item_Category_ID;

    /** @ORM\ManyToMany(targetEntity="App\Entity\Wood", mappedBy="Item_ID") */
    private $Wood_ID;

    /** @ORM\ManyToMany(targetEntity="App\Entity\Image", mappedBy="Item") */
    private $images;

    /** @ORM\OneToMany(targetEntity="App\Entity\Wishlist", mappedBy="item", orphanRemoval=true) */
    private $wishlists;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=0)
     */
    private $length;

    public function __construct()
    {
        $this->Item_Category_ID = new ArrayCollection();
        $this->Wood_ID = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->wishlists = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getWidth()
    {
        return $this->width;
    }

    public function setWidth($width): self
    {
        $this->width = $width;

        return $this;
    }

    public function getHeight()
    {
        return $this->height;
    }

    public function setHeight($height): self
    {
        $this->height = $height;

        return $this;
    }

    public function getItemAmount(): ?int
    {
        return $this->item_amount;
    }

    public function setItemAmount(int $item_amount): self
    {
        $this->item_amount = $item_amount;

        return $this;
    }

    public function getItemPrice()
    {
        return $this->item_price;
    }

    public function setItemPrice($item_price): self
    {
        $this->item_price = $item_price;

        return $this;
    }

    public function getOrderRowID(): ?OrderRow
    {
        return $this->Order_Row_ID;
    }

    public function setOrderRowID(?OrderRow $Order_Row_ID): self
    {
        $this->Order_Row_ID = $Order_Row_ID;

        return $this;
    }

    /**
     * @return Collection|ItemCategory[]
     */
    public function getItemCategoryID(): Collection
    {
        return $this->Item_Category_ID;
    }

    public function addItemCategoryID(ItemCategory $itemCategoryID): self
    {
        if (!$this->Item_Category_ID->contains($itemCategoryID)) {
            $this->Item_Category_ID[] = $itemCategoryID;
            $itemCategoryID->addItemID($this);
        }

        return $this;
    }

    public function removeItemCategoryID(ItemCategory $itemCategoryID): self
    {
        if ($this->Item_Category_ID->contains($itemCategoryID)) {
            $this->Item_Category_ID->removeElement($itemCategoryID);
            $itemCategoryID->removeItemID($this);
        }

        return $this;
    }

    /**
     * @return Collection|Wood[]
     */
    public function getWoodID(): Collection
    {
        return $this->Wood_ID;
    }

    public function addWoodID(Wood $woodID): self
    {
        if (!$this->Wood_ID->contains($woodID)) {
            $this->Wood_ID[] = $woodID;
            $woodID->addItemID($this);
        }

        return $this;
    }

    public function removeWoodID(Wood $woodID): self
    {
        if ($this->Wood_ID->contains($woodID)) {
            $this->Wood_ID->removeElement($woodID);
            $woodID->removeItemID($this);
        }

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->addItem($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            $image->removeItem($this);
        }

        return $this;
    }

    /**
     * @return Collection|Wishlist[]
     */
    public function getWishlists(): Collection
    {
        return $this->wishlists;
    }

    public function addWishlist(Wishlist $wishlist): self
    {
        if (!$this->wishlists->contains($wishlist)) {
            $this->wishlists[] = $wishlist;
            $wishlist->setItem($this);
        }

        return $this;
    }

    public function removeWishlist(Wishlist $wishlist): self
    {
        if ($this->wishlists->contains($wishlist)) {
            $this->wishlists->removeElement($wishlist);
            // set the owning side to null (unless already changed)
            if ($wishlist->getItem() === $this) {
                $wishlist->setItem(null);
            }
        }

        return $this;
    }

    public function getLength()
    {
        return $this->length;
    }

    public function setLength($length): self
    {
        $this->length = $length;

        return $this;
    }
}

src/Entity/Wood.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\WoodRepository")
 */
class Wood
{
    public function __toString()
    {
        return $this->getWood();
    }

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /** @ORM\Column(type="string", length=255) */
    private $Wood;

    /** @ORM\ManyToMany(targetEntity="App\Entity\Item", inversedBy="Wood_ID") */
    private $Item_ID;

    /** @ORM\ManyToMany(targetEntity="App\Entity\Image", mappedBy="Wood") */
    private $images;

    public function __construct()
    {
        $this->Item_ID = new ArrayCollection();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getWood(): ?string
    {
        return $this->Wood;
    }

    public function setWood(string $Wood): self
    {
        $this->Wood = $Wood;

        return $this;
    }

    /**
     * @return Collection|Item[]
     */
    public function getItemID(): Collection
    {
        return $this->Item_ID;
    }

    public function addItemID(Item $itemID): self
    {
        if (!$this->Item_ID->contains($itemID)) {
            $this->Item_ID[] = $itemID;
        }

        return $this;
    }

    public function removeItemID(Item $itemID): self
    {
        if ($this->Item_ID->contains($itemID)) {
            $this->Item_ID->removeElement($itemID);
        }

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->addWood($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            $image->removeWood($this);
        }

        return $this;
    }
}

src/Controller/Rest/Item/DeleteImageFromItem.php
<?php

declare(strict_types=1);

namespace App\Controller\Rest\Item;

use App\Entity\Image;
use App\Entity\Item;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\View\View;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

class DeleteImageFromItem extends AbstractController
{
    /**
     * @Rest\Delete("/remove_image_from_item")
     */
    public function deleteItem(Request $request): View
    {
        $em = $this->getDoctrine()->getManager();

        $itemID = $request->get('item_id');
        $imageID = $request->get('image_id');

        if (!$itemID || !$imageID) {
            return View::create('not enough data', 404);
        }

        $item = $em->getRepository(Item::class)->find($itemID);
        $image = $em->getRepository(Image::class)->find($imageID);

        if (!$item || !$image) {
            return View::create('not found', 404);
        }

        if (!$item->getImages()->contains($image)) {
            return View::create('image not found in item', 404);
        }

        $item->getImages()->removeElement($item);
        $em->remove($image);
        $em->persist($item);
        $em->flush();

        return View::create('ok', 201);
    }
}

src/Controller/Rest/Item/DeleteItemFromBasket.php
<?php

declare(strict_types=1);

namespace App\Controller\Rest\Item;

use App\Entity\Item;
use App\Entity\OrderRow;
use App\Entity\Orders;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\View\View;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

class DeleteItemFromBasket extends AbstractController
{
    /**
     * @Rest\Delete("/remove_item_from_basket")
     */
    public function deleteItem(Request $request): View
    {
        $em = $this->getDoctrine()->getManager();

        $basketID = $request->get('basket_id');
        $itemID = $request->get('product_id');

        if (!$basketID || !$itemID) {
            return View::create('Not enough data', 404);
        }

        $basket = $em->getRepository(Orders::class)->find($basketID);

        if (!$basket) {
            return View::create('Not found', 404);
        }

        $item = $em->getRepository(Item::class)->find($itemID);
        if (!$item) {
            return View::create('Not found', 404);
        }

        /** @var OrderRow $orderRowWithItem */
        $orderRowWithItem = $em->getRepository(OrderRow::class)->createQueryBuilder('orderrow')
            ->leftJoin('orderrow.Order_ID', 'userOrder')
            ->leftJoin('orderrow.Item_ID', 'itemId')
            ->where('orderrow.Order_ID = :orderID')
            ->andWhere('userOrder.isFinished = false')
            ->andWhere('itemId.id = :item_id')
            ->setParameter('orderID', $basketID)
            ->setParameter('item_id', $itemID)
            ->getQuery()
            ->getOneOrNullResult()
        ;

        if (!$orderRowWithItem->getItemID($item)) {
            return View::create('Not found', 404);
        }

        $order = $orderRowWithItem->getOrderID();
        $currentPrice = $order->getSumPrice();

        /** @var Item $item */
        $item = $orderRowWithItem->getItemID()->first();

        $itemPrice = $item->getItemPrice();
        $itemQuantity = $orderRowWithItem->getQuantity();

        $newPrice = $currentPrice - $itemPrice * $itemQuantity;

        $order->setSumPrice($newPrice);
        $newQuantity = $order->getTotalQuantity() - $itemQuantity;
        $order->setTotalQuantity($newQuantity);
        $orderRowWithItem->removeItemID($item);

        if ($orderRowWithItem->getItemID()->isEmpty()) {
            $em->remove($orderRowWithItem);
        } else {
            $em->persist($orderRowWithItem);
        }
        $em->flush();

        return View::create('ok', 201);
    }

    /**
     * @Rest\Delete("/remove_one_item_from_basket")
     */
    public function deleteOneItem(Request $request): View
    {
        $em = $this->getDoctrine()->getManager();

        $basketID = $request->get('basket_id');
        $itemID = $request->get('product_id');

        if (!$basketID || !$itemID) {
            return View::create('Not enough data', 404);
        }

        $basket = $em->getRepository(Orders::class)->find($basketID);

        if (!$basket) {
            return View::create('Not found', 404);
        }

        $item = $em->getRepository(Item::class)->find($itemID);

        if (!$item) {
            return View::create('Not found', 404);
        }

        /** @var OrderRow $orderRowWithItem */
        $orderRowWithItem = $em->getRepository(OrderRow::class)->createQueryBuilder('orderrow')
            ->leftJoin('orderrow.Order_ID', 'userOrder')
            ->leftJoin('orderrow.Item_ID', 'itemId')
            ->where('orderrow.Order_ID = :orderID')
            ->andWhere('userOrder.isFinished = false')
            ->andWhere('itemId.id = :item_id')
            ->setParameter('orderID', $basketID)
            ->setParameter('item_id', $itemID)
            ->getQuery()
            ->getOneOrNullResult()
        ;

        if (!$orderRowWithItem) {
            return View::create('Order row not found', 404);
        }

        if (!$orderRowWithItem->getItemID($item)) {
            return View::create('Not found item in order', 404);
        }

        $order = $orderRowWithItem->getOrderID();
        $currentPrice = $order->getSumPrice();

        /** @var Item $item */
        $item = $orderRowWithItem->getItemID()->first();

        $itemPrice = $item->getItemPrice();
        $itemQuantity = $orderRowWithItem->getQuantity() - 1;
        $orderRowWithItem->setQuantity($itemQuantity);

        $newPrice = $currentPrice - $itemPrice;

        $order->setSumPrice($newPrice);
        $newQuantity = $order->getTotalQuantity() - 1;
        $order->setTotalQuantity($newQuantity);

        if ($orderRowWithItem->getItemID()->isEmpty() || $orderRowWithItem->getQuantity() <= 0) {
            $orderRowWithItem->removeItemID($item);
            $em->remove($orderRowWithItem);

            if ($order->getOrderRowID()->isEmpty()) {
                $em->remove($order);
            }
        } else {
            $em->persist($orderRowWithItem);
        }

        $em->flush();

        return View::create($order->getTotalQuantity(), 201);
    }
}

src/Controller/Rest/Item/ItemCreate.php
<?php

declare(strict_types=1);

namespace App\Controller\Rest\Item;

use App\Entity\Item;
use App\Entity\OrderRow;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\View\View;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

class ItemCreate extends AbstractController
{
    /**
     * @Rest\Post("/item")
     */
    public function postItem(Request $request): View
    {
        $item = new Item();
        $em = $this->getDoctrine()->getManager();

        $item->setDescription($request->get('description'));
        $item->setHeight('height');
        $item->setImg('img');
        $item->setItemAmount('item_amount');
        $item->setItemPrice('item_price');
        $item->setName('name');
        $orderRowRepository = $em->getRepository(OrderRow::class);

        /** @var OrderRow $orderRow */
        $orderRow = $orderRowRepository->find($request->get('order_row'));
        $item->setOrderRowID($orderRow);
        $item->setWidth('width');

        $em->persist($item);
        $em->flush();

        return View::create($item, 201);
    }
}

src/Controller/Rest/Item/ItemRead.php
<?php

declare(strict_types=1);

namespace App\Controller\Rest\Item;

use App\Entity\Item;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\View\View;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

class ItemRead extends AbstractController
{
    /**
     * @Rest\Get("/item/{itemID}")
     */
    public function getItem(int $itemID): View
    {
        $em = $this->getDoctrine()->getManager();
        $item = $em->getRepository(Item::class)->find($itemID);
        if ($item) {
            return View::create($item, 201);
        }

        return View::create('Not found', 404);
    }

    public function readItems(Request $request)
    {
    }
}

templates/item/createItem.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ItemController!
{% endblock %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}
<style>
    .example-wrapper {
        margin: 1em auto;
        max-width: 800px;
        width: 95%;
        font: 18px / 1.5 sans-serif;
    }
    .example-wrapper code {
        background: #F5F5F5;
        padding: 2px 6px;
    }
</style>

<div class="example-wrapper">
    {{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.description) }}
    {{ form_row(form.width) }}
    {{ form_row(form.height) }}
    {{ form_row(form.length) }}
    {{ form_row(form.item_amount) }}
    {{ form_row(form.item_price) }}
    {{ form_row(form.wood) }}
    {{ form_label(form.images) }}
    <ul class="images" data-prototype="{{ form_widget(form.images.vars.prototype)|e('html_attr') }}">
        <li>{{ form_widget(form.images) }}
        </li>
    </ul>
    {{ form_row(form.submit) }}
    {{ form_end(form) }}
</div>

<script>
    // setup an "add a tag" link
    var $addImageLink = $('<a href="#" class="add_image_link btn btn-primary">Add an image</a>');
    var $newLinkLi = $('<li></li>').append($addImageLink);

    jQuery(document).ready(function () { // Get the ul that holds the collection of tags
        var $collectionHolder = $('ul.images');

        // add the "add a tag" anchor and li to the tags ul
        $collectionHolder.append($newLinkLi);

        // count the current form inputs we have (e.g. 2), use that as the new
        // index when inserting a new item (e.g. 2)
        $collectionHolder.data('index', $collectionHolder.find(':input').length);

        $addImageLink.on('click', function (e) { // prevent the link from creating a "#" on the URL
            e.preventDefault();

            // add a new tag form (see code block below)
            addImageForm($collectionHolder, $newLinkLi);
        });

        $('.remove-image').click(function (e) {
            e.preventDefault();

            $(this).parent().remove();

            return false;
        });

        function addImageForm($collectionHolder, $newLinkLi) { // Get the data-prototype explained earlier
            var prototype = $collectionHolder.data('prototype');

            // get the new index
            var index = $collectionHolder.data('index');

            // Replace '$$name$$' in the prototype's HTML to
            // instead be a number based on how many items we have
            var newForm = prototype.replace(/__name__/g, index);

            // increase the index with one for the next item
            $collectionHolder.data('index', index + 1);

            // Display the form in the page in an li, before the "Add a tag" link li
            var $newFormLi = $('<li></li>').append(newForm);

            // also add a remove button, just for this example
            $newFormLi.append('<a href="#" class="remove-image">x</a>');

            $newLinkLi.before($newFormLi);

            // handle the removal, just for this example
            $('.remove-image').click(function (e) {
                e.preventDefault();

                $(this).parent().remove();

                return false;
            });
        }
    });
    </script>
{% endblock %}

templates/item/editItem.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ItemController!{% endblock %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    {{ form_start(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.description) }}
    {{ form_row(form.width) }}
    {{ form_row(form.height) }}
    {{ form_row(form.length) }}
    {{ form_row(form.item_amount) }}
    {{ form_row(form.item_price) }}
    {{ form_row(form.wood) }}
    {{ form_label(form.images) }}
    <ul class="images" data-prototype="{{ form_widget(form.images.vars.prototype)|e('html_attr') }}">
        <li>{{ form_widget(form.images) }}
        </li>
    </ul>
    {% for image in images %}
        {% set image_url = 'uploads/images/' ~ image.source %}
        <img width="100px" height="100px" src="{{ asset(image_url) }}">
        <a onclick="removeImage({{ item_id }}, {{ image.id }})" class="btn btn-danger" href="#">delete</a>
    {% endfor %}
    {{ form_row(form.submit) }}
    {{ form_end(form) }}
</div>

<script>
    function removeImage(itemID, imageID) {
        route = '/api/remove_image_from_item';

        $.ajax
        ({
            url: route,
            type: 'delete',
            data: {
                "item_id": itemID,
                "image_id": imageID
            },
            success: function(result)
            {
                alert('deleted ' + result);
                location.reload();
            }
        });
    }

    // setup an "add a tag" link
    var $addImageLink = $('<a href="#" class="add_image_link btn btn-primary">Add an image</a>');
    var $newLinkLi = $('<li></li>').append($addImageLink);

    jQuery(document).ready(function() {
        // Get the ul that holds the collection of tags
        var $collectionHolder = $('ul.images');

        // add the "add a tag" anchor and li to the tags ul
        $collectionHolder.append($newLinkLi);

        // count the current form inputs we have (e.g. 2), use that as the new
        // index when inserting a new item (e.g. 2)
        $collectionHolder.data('index', $collectionHolder.find(':input').length);

        $addImageLink.on('click', function(e) {
            // prevent the link from creating a "#" on the URL
            e.preventDefault();

            // add a new tag form (see code block below)
            addImageForm($collectionHolder, $newLinkLi);
        });

        {% if app.request.get('_route') == 'item_edit' %}
            $('.remove-image').click(function(e) {
                e.preventDefault();

                $(this).parent().remove();

                return false;
            });
        {% endif %}
    });

    function addImageForm($collectionHolder, $newLinkLi) {
        // Get the data-prototype explained earlier
        var prototype = $collectionHolder.data('prototype');

        // get the new index
        var index = $collectionHolder.data('index');

        // Replace '$$name$$' in the prototype's HTML to
        // instead be a number based on how many items we have
        var newForm = prototype.replace(/__name__/g, index);

        // increase the index with one for the next item
        $collectionHolder.data('index', index + 1);

        // Display the form in the page in an li, before the "Add a tag" link li
        var $newFormLi = $('<li></li>').append(newForm);

        // also add a remove button, just for this example
        $newFormLi.append('<a href="#" class="remove-image">x</a>');

        $newLinkLi.before($newFormLi);

        // handle the removal, just for this example
        $('.remove-image').click(function(e) {
            e.preventDefault();

            $(this).parent().remove();

            return false;
        });
    }
</script>
{% endblock %}

templates/item/items.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ItemController!{% endblock %}

{% block body %}

<div id="aside" class="col-md-3">
<!-- aside Widget -->
<div class="aside">
    <h3 class="aside-title">Categories</h3>
    <div class="checkbox-filter">
    {% set item_categoties = get_categories_with_count() %}
        {% for item_category in item_categoties %}
        <div class="input-checkbox">
            <input class="category-checkbox" id="category-{{ item_category.category.getid() }}" data-id={{ item_category.category.getid() }} type="checkbox">
            <label for="category-{{ item_category.category.getid() }}">
                <span></span>
                {{ item_category.category.category }}
                <small>({{ item_category.count }})</small>
            </label>
        </div>
        {% endfor %}
    </div>
</div>
<!-- /aside Widget -->

</div>

{% if items is defined %}
<div class="col-md-9">
    {% for item in items %}
    {% set categoryId = 0 %}
    {% for itemcategory in item.itemcategoryid %}
    {% set categoryId = itemcategory.id %}
    {% endfor %}
    <div class="col-md-4 col-xs-6 item" data-category-id={{categoryId}}>
        <div class="product" style="width: 263px;">
            <div class="product-img">
                {% set item_images = item.images %}
                {% if item_images[0] is defined %}
                    {% set image_url = 'uploads/images/' ~ item_images[0].source %}
                    <img src="{{ asset(image_url) }}" alt="">
                {% endif %}
            </div>
            <div class="product-body">
                <p class="product-category">{{ item.woodid[0].wood }}</p>
                <h3 class="product-name"><a href="{{ path('item_read', {'itemID': item.id}) }}">{{ item.name }}</a></h3>
                <h4 class="product-price">{{ item.itemprice }}zł <del class="product-old-price">{{ item.itemprice * 2 }}zł</del></h4>
                <div class="product-rating">
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                    <i class="fa fa-star"></i>
                </div>
                <div class="product-btns">
                    <button class="add-to-wishlist" tabindex="0" data-itemid="{{ item.id }}"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
                    <button class="quick-view" tabindex="0"><i class="fa fa-eye"></i><span class="tooltipp">view details (LINK DO PRODUKTU)</span></button>
                </div>
            </div>
            {% if app.user %}

            <div class="add-to-cart">
                <button class="add-to-cart-btn" tabindex="0" data-id={{item.id}} data-orderid="{% if order.id is defined and not null %}{{ order.id }}{% endif %}"><i class="fa fa-shopping-cart"></i> add to cart</button>
            </div>
            {% endif %}

        </div>
    </div>
    {% endfor %}
</div>
{% if app.user %}
    <script>
        $('.add-to-cart-btn').click(function () {
            let user = {{ app.user.id }};
            let product = $(this).data("id");
            //console.log(product)
            let route = '/api/add_to_basket';
            let order_id = $(this).data('orderid');

            $.ajax({
                url: route,
                type: 'post',
                data: {
                    "user_id": user,
                    "product_id": product,
                    "product_quantity": 1
                },
                success: function (result) {
                    let cartAmountDiv = document.getElementById("cart_amount");

                    if (parseInt(result) > 0) {
                        if (cartAmountDiv === null) {
                            let cartAmountLinkDiv = document.getElementById("cart_amount_link");
                            let newDiv = document.createElement("div");
                            newDiv.id = "cart_amount";
                            newDiv.className = "qty";
                            cartAmountLinkDiv.appendChild(newDiv);

                            cartAmountDiv = document.getElementById("cart_amount");
                        }

                        cartAmountDiv.innerHTML = result.toString();
                        $('.cart-summary-amount').html(result.toString());
                    } else {
                        if (cartAmountDiv !== null) {
                            cartAmountDiv.parentNode.removeChild(cartAmountDiv);
                        }
                    }
                }
            });
            let new_route = '/api/get_order_amount/' + order_id;
            console.log(new_route);
            $.ajax({
                url: new_route,
                type: 'get',
                success: function (result) {
                    $('.cart-summary-subtotal').html(result.toString());
                }
            });
        })

        $('.add-to-wishlist').click(function() {
            let user = {{ app.user.id }};
            let route = '/api/add_to_wishlist';
            let item_id = $(this).data('itemid');
            $.ajax({
                url: route,
                type: 'post',
                data: {
                    "user_id": user,
                    "item_id": item_id,
                },
                success: function (result) {
                    let cartAmountDiv = document.getElementById("wishlist_amount");

                    if (parseInt(result) > 0) {
                        if (cartAmountDiv === null) {
                            let cartAmountLinkDiv = document.getElementById("wishlist_amount_link");
                            let newDiv = document.createElement("div");
                            newDiv.id = "wishlist_amount";
                            newDiv.className = "qty";
                            cartAmountLinkDiv.appendChild(newDiv);

                            cartAmountDiv = document.getElementById("wishlist_amount");
                        }

                        cartAmountDiv.innerHTML = result.toString();
                    } else {
                        if (cartAmountDiv !== null) {
                            cartAmountDiv.parentNode.removeChild(cartAmountDiv);
                        }
                    }
                }
            });
        })
    </script>
{% endif %}

<script>
function checkboxes() {
    isAnyChecked = false;
    $(".category-checkbox").each(function(){
        if($(this).is(":checked")){
            isAnyChecked = true;
            categoryId = $(this).data("id")
            $(".item").each(function() {
                itemCategoryId = $(this).data("category-id")
                if(itemCategoryId == categoryId) {
                    $(this).show()
                } else {
                    $(this).hide()
                }
            });
        }
    });
    categoryId = $(this).data("id")
    if(!isAnyChecked) {
            $(".item").each(function() {
            $(this).show();
        });
    }
}

$(document).ready(checkboxes);

$(".category-checkbox").change(checkboxes);
</script>

{% endif %}
{% endblock %}