src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"login"}, message="There is already an account with this login")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /** @ORM\Column(type="string", length=180, unique=true) */
    private $uuid;

    /** @ORM\Column(type="json") */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /** @ORM\Column(type="string", length=255) */
    private $login;

    /** @ORM\Column(type="string", length=255) */
    private $email;

    /** @ORM\Column(type="string", length=255) */
    private $NIP;

    /** @ORM\Column(type="boolean") */
    private $Company_Account;

    /** @ORM\Column(type="string", length=255, nullable=true) */
    private $Company_Name;

    /** @ORM\OneToMany(targetEntity="App\Entity\Orders", mappedBy="User_ID") */
    private $Order_ID;

    /** @ORM\OneToMany(targetEntity="App\Entity\Wishlist", mappedBy="user", orphanRemoval=true) */
    private $wishlists;

    public function __construct()
    {
        $this->Order_ID = new ArrayCollection();
        $this->wishlists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->uuid;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLogin(): ?string
    {
        return $this->login;
    }

    public function setLogin(string $login): self
    {
        $this->login = $login;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getNIP(): ?string
    {
        return $this->NIP;
    }

    public function setNIP(string $NIP): self
    {
        $this->NIP = $NIP;

        return $this;
    }

    public function getCompanyAccount(): ?bool
    {
        return $this->Company_Account;
    }

    public function setCompanyAccount(bool $Company_Account): self
    {
        $this->Company_Account = $Company_Account;

        return $this;
    }

    public function getCompanyName(): ?string
    {
        return $this->Company_Name;
    }

    public function setCompanyName(?string $Company_Name): self
    {
        $this->Company_Name = $Company_Name;

        return $this;
    }

    /**
     * @return Collection|Orders[]
     */
    public function getOrderID(): Collection
    {
        return $this->Order_ID;
    }

    public function addOrderID(Orders $orderID): self
    {
        if (!$this->Order_ID->contains($orderID)) {
            $this->Order_ID[] = $orderID;
            $orderID->setUserID($this);
        }

        return $this;
    }

    public function removeOrderID(Orders $orderID): self
    {
        if ($this->Order_ID->contains($orderID)) {
            $this->Order_ID->removeElement($orderID);
            // set the owning side to null (unless already changed)
            if ($orderID->getUserID() === $this) {
                $orderID->setUserID(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Wishlist[]
     */
    public function getWishlists(): Collection
    {
        return $this->wishlists;
    }

    public function addWishlist(Wishlist $wishlist): self
    {
        if (!$this->wishlists->contains($wishlist)) {
            $this->wishlists[] = $wishlist;
            $wishlist->setUser($this);
        }

        return $this;
    }

    public function removeWishlist(Wishlist $wishlist): self
    {
        if ($this->wishlists->contains($wishlist)) {
            $this->wishlists->removeElement($wishlist);
            // set the owning side to null (unless already changed)
            if ($wishlist->getUser() === $this) {
                $wishlist->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/Rest/User/UserCreate.php
<?php

declare(strict_types=1);

namespace App\Controller\Rest\User;

use App\Entity\User;
use App\Helper\StringGenerator;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\View\View;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

class UserCreate extends AbstractController
{
    /** @var StringGenerator */
    private $stringGenerator;

    public function __construct(StringGenerator $stringGenerator)
    {
        $this->stringGenerator = $stringGenerator;
    }

    /**
     * @Rest\Post("/user")
     */
    public function postUser(Request $request): View
    {
        $data = json_decode($request->getContent(), true);
        /** @var User $user */
        $user = new User();

        $user->setLogin($data['login']);
        $user->setEmail($data['email']);
        $password = password_hash($data['password'], \PASSWORD_BCRYPT);
        $user->setPassword($password);
        $user->setCompanyAccount($data['company_account']);
        if (false == $data['company_account']) {
            $user->setCompanyName($data['company_name']);
        }
        $user->setNIP($data['nip']);
        $uuid = $this->stringGenerator->generateNumbers(10);
        $user->setUuid($uuid);
        $em = $this->getDoctrine()->getManager();
        $em->persist($user);
        $em->flush();

        return View::create(json_encode($data), 201);
    }
}

src/Controller/Rest/User/UserDelete.php
<?php

declare(strict_types=1);

namespace App\Controller\Rest\User;

use App\Entity\User;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\View\View;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class UserDelete extends AbstractController
{
    /**
     * @Rest\Delete("/user/{uuid}", requirements={"uuid"="\d+"})
     */
    public function getItem(int $uuid): View
    {
        $em = $this->getDoctrine()->getManager();
        /** @var User $user */
        $user = $em->getRepository(User::class)->findOneBy(['uuid' => $uuid]);

        if (null != $user) {
            $em->remove($user);
            $em->flush();

            return View::create('removed', 200);
        }

        return View::create('Not found', 404);
    }
}

src/Controller/Rest/User/UserRead.php
<?php

declare(strict_types=1);

namespace App\Controller\Rest\User;

use App\Entity\User;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\View\View;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class UserRead extends AbstractController
{
    /**
     * @Rest\Get("/user/{uuid}", requirements={"uuid"="\d+"})
     */
    public function getItem(int $uuid): View
    {
        $em = $this->getDoctrine()->getManager();
        /** @var User $user */
        $user = $em->getRepository(User::class)->findOneBy(['uuid' => $uuid]);

        if ($user) {
            $userArray = [
                'login' => $user->getLogin(),
                'company_account' => $user->getCompanyAccount(),
                'uuid' => $user->getUuid(),
                'email' => $user->getEmail(),
                'nip' => $user->getNIP(),
            ];

            return View::create(json_encode($userArray, \JSON_PRETTY_PRINT), 200);
        }

        return View::create('Not found', 404);
    }
}

src/Controller/Rest/User/UserUpdate.php
<?php

declare(strict_types=1);

namespace App\Controller\Rest\User;

use App\Entity\User;
use FOS\RestBundle\Controller\Annotations as Rest;
use FOS\RestBundle\View\View;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;

class UserUpdate extends AbstractController
{
    /**
     * @Rest\Put("/user/{uuid}", requirements={"uuid"="\d+"})
     */
    public function getItem(Request $request, int $uuid): View
    {
        $data = json_decode($request->getContent(), true);
        $em = $this->getDoctrine()->getManager();
        /** @var User $user */
        $user = $em->getRepository(User::class)->findOneBy(['uuid' => $uuid]);

        if (null != $user) {
            $user->setLogin($data['login']);
            $user->setEmail($data['email']);
            $password = password_hash($data['password'], \PASSWORD_BCRYPT);
            $user->setPassword($password);
            $user->setCompanyAccount($data['company_account']);
            if (false == $data['company_account']) {
                $user->setCompanyName($data['company_name']);
            }
            if ($data['role']) {
                $user->setRoles(['ROLE_ADMIN']);
            }
            $user->setNIP($data['nip']);

            return View::create('ok', 200);
        }

        return View::create('Not found', 404);
    }
}

src/Controller/Web/UserController.php
<?php

declare(strict_types=1);

namespace App\Controller\Web;

use App\Entity\Orders;
use App\Entity\User;
use App\Form\RegistrationFormType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class UserController extends AbstractController
{
    /**
     * @Route("/user/{uuid}", name="user", requirements={"uuid"="\d+"})
     */
    public function index(int $uuid): Response
    {
        $em = $this->getDoctrine()->getManager();
        $user = $em->getRepository(User::class)->find($uuid);

        if (!$user) {
            return $this->render('error.html.twig', [
                'exception' => 'not found',
                'exceptionTitle' => 'error',
            ]);
        }

        return $this->render('user/index.html.twig', [
            'user' => $user,
        ]);
    }

    /**
     * @Route("/my_orders", name="user_orders")
     */
    public function myOrders(): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        if (!$user) {
            return $this->render('error.html.twig', [
                'exceptionTitle' => 'not logged in',
                'exception' => 'this page is for registered users only',
            ]);
        }

        $em = $this->getDoctrine()->getManager();

        $orders = $em->getRepository(Orders::class)->createQueryBuilder('o')
            ->where('o.User_ID = :userid')
            ->setParameter('userid', $user->getId())
            ->getQuery()
            ->execute()
        ;

        return $this->render('user/userOrders.html.twig', [
            'orders' => $orders,
        ]);
    }

    /**
     * @Route("/user/edit", name="user_edit")
     */
    public function editUser(Request $request): Response
    {
        /** @var User $user */
        $user = $this->getUser();

        $em = $this->getDoctrine()->getManager();

        $userData = $em->getRepository(User::class)->find($user->getId());

        if (!$userData) {
            return $this->render('error.html.twig', [
                'exception' => 'Not correct user',
                'exceptionTitle' => 'Invalid user',
            ]);
        }

        $editForm = $this->createForm(RegistrationFormType::class, $userData);

        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {
            $data = $editForm->getData();

            $em->persist($data);
            $em->flush();

            return $this->redirectToRoute('home');
        }

        return $this->render('user/userEdit.html.twig', [
            'editForm' => $editForm->createView(),
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    {{ dump(user) }}
</div>
{% endblock %}

templates/user/userEdit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
    <div class="section-title">
        <h1 class="title">Edit account</h1>
    </div>

    {{ form_start(editForm) }}
        <div class="form-group">
        {{ form_row(editForm.login, { 'attr': {'class': 'input'} }) }}
        </div>
        <div class="form-group">
        {{ form_row(editForm.plainPassword, { 'attr': {'class': 'input'} }) }}
        </div>
        <div class="form-group">
        {{ form_row(editForm.email, { 'attr': {'class': 'input'} }) }}
        </div>
        <div class="form-group">
        {{ form_row(editForm.companyAccount, { 'attr': {'class': 'input'} }) }}
        </div>
        <div class="form-group">
        {{ form_row(editForm.companyName, { 'attr': {'class': 'input'} }) }}
        </div>
        <div class="form-group">
        {{ form_row(editForm.nIP, { 'attr': {'class': 'input'} }) }}
        </div>
        <button class="primary-btn order-submit">Save</button>
    {{ form_end(editForm) }}
{% endblock %}

templates/user/userOrders.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello OrderController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }
    </style>

    <div class="example-wrapper" style="font-family: Montserrat, sans-serif;">
        {% for userOrder in orders %}
        <h3 class="aside-title"
            style="font-family: Montserrat, sans-serif; text-transform: uppercase">{{ "Order number: " ~ userOrder.id }}
        </h3>
        <span>Order price: {{ userOrder.sumprice }} ZŁ</span>
        <br/>
        <span>Ordered products:</span>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Product</th>
                <th>Quantity</th>
            </tr>
            </thead>
            <tbody>
            {% for orderRow in userOrder.orderRowId %}
                {% for item in orderRow.itemid %}
                    <tr>
                        {# <h4 class="product-name" style="font-family: Montserrat, sans-serif;"> #}
                        <th>{{ item.id }}</th>
                        <td>
                            <a href="{{ path('item_read', {'itemID': item.id}) }}">{{ item.name }}</a>
                        </td>
                        <td>
                            {{ orderRow.getQuantity() }}
                        </td>
                        {# </h4> #}
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
        <br/>
        {% endfor %}
    </div>
{% endblock %}